name = "amortizable-sale-ext"
type = "order_discounts"
api_version = "2022-07"

[build]
command = "cargo wasi build --release"
path = "target/wasm32-wasi/release/amortizable-sale-ext.wasm"

[ui.paths]
create = "/"
details = "/"
